### ISSUE TITLE
Ошибка при обработке метода с аннотацией @Step в shouldThrow

### ISSUE THREAD

**Issue by CrazyMoonkin** [kochetkov-ma/kotest-allure#7]
Если в блоке `shouldThrow` для проверки выбрасывания исключения методом помеченным аннотацией `@Step`, то весь кейс в отчете получит статус Broken, но при этом Kotest считает его успешным.

Пример теста
```kotlin
class ExampleStringSpec : StringSpec() {

    init {
        "Some test case description" {
            shouldThrow<Exception> { throwException() }
        }
    }

    @Step("Some step description")
    fun throwException() {
        throw Exception()
    }
}
```
Результат выполнения в IDE:
![изображение](https://user-images.githubusercontent.com/30863968/206895409-2ac87981-0f50-4e9b-a7d5-dc544d371065.png)

Результат в отчете:
![изображение](https://user-images.githubusercontent.com/30863968/206895448-3d1fcbfe-e0d9-467f-9b9b-5009a3386676.png)

**Comment by kochetkov-ma** [comment]
Thanks, @CrazyMoonkin, for the original report. The `@Step` exception caught by `shouldThrow` is fixed in [v6.2.5](https://github.com/kochetkov-ma/kotest-allure/releases/tag/v6.2.5), available on [Maven Central](https://repo1.maven.org/maven2/ru/iopump/kotest/kotest-allure/6.2.5/). The Allure test case now stays `passed`, while the annotated step retains `broken` and the exception details. This is asserted by the [regression contract](https://github.com/kochetkov-ma/kotest-allure/blob/v6.2.5/src/test/kotlin/ru/iopump/kotest/allure/AllureGeneratedResultContractSpec.kt#L56-L60), passed in [release CI](https://github.com/kochetkov-ma/kotest-allure/actions/runs/35452189391), and independently verified against the published Central JAR with a clean Java 21/Kotest 6.2.5 consumer. The issue was already closed; this comment records the released fix.
